### PR TITLE
checking if something is not a number is not simple when doing recursion in your 2nd day of JS

### PR DESCRIPTION
**Pull request by Fenntasy**

### CODE REVIEW

**Comment by arnaudmorisset** [comment]
`const is_number = (x) => (typeof x === "number") && !isNaN(x);`

Too complex at this time? 🤔

**Comment by Fenntasy** [comment]
Well `Infinity` still passes (and good luck doing a factorial on that :p) and it's their second day ^^

**Comment by arnaudmorisset** [comment]
```javascript
const is_number = (x) => (typeof x === "number") && !isNaN(x) && isFinite(x);
```
😬 

But okay, maybe I'm a little mean with them.

**Comment by phink** [comment]
```js
const is_number = (x) => (typeof x === "number") && isFinite(x);
```
should be enough ;p

**Comment by Fenntasy** [comment]
Well we can still go shorter

```javascript
const is_number = x => (typeof x === "number") && isFinite(x)
```

but still ^^'

**Comment by Fenntasy** [comment]
Let me change the title of this PR

**Pull request merged**
